### ISSUE TITLE
How do i run the code?

### ISSUE THREAD

**Issue by yusra-shaikh** [jameslyons/python_speech_features#26]
is the entire code that will extract the features present in example.py?
or is that just a portion of the code?. also, where will the features be extracted?

**Comment by jameslyons** [comment]
If you can run the code in example.py without errors, then it means
everything is good. If you do get errors it probably means you havn't
installed python_speech_features properly. The features are stored in the
variable mfcc_feat.You can do whatever you want with that variable e.g.
write it to a file or use it in a classifier.
