### ISSUE TITLE
No delta?

### ISSUE THREAD

**Issue by naman1901** [jameslyons/python_speech_features#28]
If I try to import the `delta` module, my IDE flags it as unresolved reference. Needless to say, trying to run the program gives the `ImportError: cannot import name 'delta'` exception.

Edit: After going through your code here on GitHub, I can see that `delta` is indeed defined. Any ideas on why I'm getting the error that I am?

Edit 2: Its got to do with the version distributed by PyPi. The base.py file there does not have the delta function defined in it. You might want to fix this. Cheers! :D

**Comment by jameslyons** [comment]
Yeah, the pypi version is slightly behind, ill update it asap. Sorry for the confusion
