### ISSUE TITLE
inconsistent result with HTK

### ISSUE THREAD

**Issue by zym1010** [jameslyons/python_speech_features#29]
Hi,

I tried to compare the MFCC features generated using HTK, and those generated by python_speech_features. Unfortunately, somehow they always mismatch.

Below is the configuration I used for HTK

~~~
SOURCEFORMAT = NIST
TARGETKIND = MFCC_0
TARGETRATE = 100000
SAVECOMPRESSED = F
SAVEWITHCRC = F
WINDOWSIZE = 250000
USEHAMMING = F
PREEMCOEF = 0.97
NUMCHANS = 26
CEPLIFTER = 22
NUMCEPS = 12
ENORMALISE = F
~~~

The configuration for `python_speech_features` is default.

I also tried adding `USEPOWER = F/T`, and still features obtained are very different (actually, for file `TIMITcorpus/TIMIT/TRAIN/DR8/FBCG1/SX442`, I got 358 frames for HTK, but only 354 frames for python_speech_features.

Any insight? I'm a newbie in speech recognition, and may have committed some silly mistakes..

**Comment by jameslyons** [comment]
The features were not implemented to be identical to htk, there will always be numeric differences. The results when used in a classifier should be similar I.e. they should contain similar information. The number of frames will depend on how much zero padding is used, and probably a couple other different things. It would simply be too hard to get exactly the same numbers, and there wouldn't be much benefit.

**Comment by zym1010** [comment]
@jameslyons I mean it's very different. I computed the pearson correlation between first 5 frames, and I only get about 0.6.

**Comment by zym1010** [comment]
@jameslyons after some debugging, I think you are right. The main reason I obtain small correlation is that somehow there's a DC shift for zero-th order MFCC between HTK and your package. If I separately compute the correlation for coefficients 1-12 and that for 0, then I got around 0.99. Thanks.

**Comment by jameslyons** [comment]
No worries :)
