### ISSUE TITLE
incorrect normalization in logpowspec

### ISSUE THREAD

**Issue by siryog90** [jameslyons/python_speech_features#35]
Hello.
I think in the logpowspec function
`    if norm:
        return lps - numpy.max(lps)
    else:
        return lps`

was supposed to be `    if norm:
        return lps / numpy.max(lps)
    else:
        return lps`

Also, consider accepting frame_len and frame_step in terms of samples rather than seconds, as this lets the user enter precise powers of two for the fft to work just right.

**Comment by jameslyons** [comment]
hi siryog90,
For the power spectrum the normalisation you suggest is correct:
normps = ps / max(ps)
once we take the log though,
normlps = log(ps/max(ps)) = log(ps) - log(max(ps) = lps - max(lps)
So we're using the properties of log to convert divisions to subtractions. 

For the FFT, you can set NFFT (this is the fft length) to be a power of 2. This zero pads the frame, so any frame length can be used, but the the FFT still uses whatever length you specify.

Cheers,
James
