### ISSUE TITLE
log() or log10() ?

### ISSUE THREAD

**Issue by dieka13** [jameslyons/python_speech_features#36]
I noticed that you use numpy.log() to compute log instead of numpy.log10(). I found another [reference](http://haythamfayek.com/2016/04/21/speech-processing-for-machine-learning.html) that use numpy.log10() instead of numpy.log(). 

numpy.log() is [natural logarithm](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html) instead of [base 10 numpy.log10()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log10.html).

Which one is correct? or it can be used interchangeably? would you explain why you choose to use log() instead of log10()? i want to extract log mel-filter-bank but i don't know which log should be used.

**Comment by jameslyons** [comment]
It doesn't matter which you use. Because log(x)=log10(x)/log(10), so they differ by a constant factor. When used in a classifier constant factors wont influence the final result.

**Comment by jameslyons** [comment]
Denominator should be log10 (e)
