### ISSUE TITLE
Length of MFCC arrays

### ISSUE THREAD

**Issue by Klervix** [jameslyons/python_speech_features#40]
Hi and thank you for these wonderful tools!

I have some troubles trying to get the same length for several MFCC arrays (for different audio files, in order to train a neural network after that).
I do  : 
```
sr, wave = wav_feat.read(path+wav)
mfcc = python_speech_features.mfcc(wave,sr,numcep=20)
```
on all my files.
So I obtain mfcc arrays of elements. All these elements contain 20 features, but how can I do to have the same size of MFCC arrays with the parameters ?

I know that sound easy but I'm a beginner...
Maybe I could use len(wave), the rate and other parameters...

Thank you very much !

**Comment by jameslyons** [comment]
Hi!
The answer to your question depends on what you are trying to do, speech recognition? Speaker identification? Emotion recognition? Or music there are a heap of other things to do.

For speech rec you will need to use either hmms or recurrent neural nets, but note that general purpose asr is really hard, see how complex kaldi is as an example. Rnns can handle variable length inputs which circumvents your problem. 

Speaker ident is done a little different, you take a block of frames and calculate the likelihood that block of frames comes from each speaker. To calculate likelyhoods for a whole file just multiply likelyhoods from each block. Other types of things can be done for other goals.

**Comment by Klervix** [comment]
I trying to do keyword spotting, so maybe my problem comes from another part of my code! I tought my problem with my network was because of this length, but I will try to find another way to correct it.
I have already trained neural networks with TFLearn for image recognition (always the same number of features), but not for sound yet. Let's practice!

Thanks a lot :)
