### ISSUE TITLE
Why am I getting double the frames that I am expecting?

### ISSUE THREAD

**Issue by SlightlyCyborg** [jameslyons/python_speech_features#42]
I have 31 second audio @ 16000hz

I run MFCC on the audio at default settings (.01s step sizes)

This should mean that I get 31s/0.01s = 3100 frames.

What I am getting as a result of calling mfcc() is 6200 frames. Am I misunderstanding something?

**Comment by SlightlyCyborg** [comment]
I am sorry. I was stereo audio. Use mono audio only!

**Comment by jameslyons** [comment]
Good to know, I don't think I've ever applied it to stereo before.
