### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ngragaei** [jameslyons/python_speech_features#49]
ImportError                               Traceback (most recent call last)
<ipython-input-12-5359effa49ad> in <module>()
      1 import python_speech_features
----> 2 from python_speech_features import mfcc
      3 from python_speech_features import delta
      4 from python_speech_features import logfbank
      5 import scipy.io.wavfile as wav

ImportError: cannot import name 'mfcc'
How can i solve this error?

**Comment by jameslyons** [comment]
you're going to have to give me some more information. Did you run the fix
I told you about last time? what version of python are you using? how are
you running the code? are you using virtualenv? can you give a small piece
of code that reproduces the problem? I have just upgraded my version using
'pip install python_speech_features --upgrade' and it runs the code just
fine.
