### ISSUE TITLE
How to turn wav in to (N,1)? 

### ISSUE THREAD

**Issue by KeyKy** [jameslyons/python_speech_features#51]
I am a newcomer to audio processing. I using 
```
wavfile.read(buf)
```

However, the audio's shape is (8127488, 2). How can i turn it into (N, 1) and feed it into the mfcc.

**Comment by jameslyons** [comment]
The two dimensions are the left and right channels. Just take the mean to get a single channel. E.g. sig = np.mean (sig, axis=1)

Also, your audio is very long. Try resampling it to 16khz using scipy.signal.resample_poly, you may need to pass smaller chunks in at a time if you run out of memory.

**Comment by cogito666** [comment]
I got a question.
Is there any reason why you didn't specify that your code only works on mono channel audio files so that everyone should check/modify before processing?
