### ISSUE TITLE
39 dimensional MFCC

### ISSUE THREAD

**Issue by dmoham1476** [jameslyons/python_speech_features#53]
I generated 13 MFCC co-efficents using mfcc().

 mfcc_feat = mfcc(audio_data, sample_rate, winlen=0.025, winstep=0.01,
                     numcep=13, nfilt=26, nfft=512, lowfreq=0, highfreq=None,
                     preemph=0.97, ceplifter=22, appendEnergy=True)

How can I get delta and delta-delta cepstrum so I can build a 39 dimensional MFCC?
Deepa

**Comment by jameslyons** [comment]
mfcc_feat = mfcc(sig,rate)
d_mfcc_feat = delta(mfcc_feat, 2)
a_mfcc_feat = delta(d_mfcc_feat, 2)

feat = np.hstack([mfcc_feat, d_mfcc_feat, a_mfcc_feat])

feat should be n by 39 dimensional matrix

**Comment by dmoham1476** [comment]
Thanks a lot!
