### ISSUE TITLE
Does python speech features have a c port? 

### ISSUE THREAD

**Issue by dmoham1476** [jameslyons/python_speech_features#56]
Wondering if we can use this lib for MFCC generation in Android NDK?

**Comment by jameslyons** [comment]
check out https://github.com/Cwiiis/c_speech_features 
I haven't had anything to do with it, you'll have to speak with the maintainer if you want to know anything about it.

**Comment by csukuangfj** [comment]
Please have a look at
https://github.com/csukuangfj/kaldi-native-fbank

It is implemented in C++ and provides both C++ and Python API.

It has been tested on
- Linux, macOS, Windows
- Android, iOS
- x86_64, aarch64, arm, RISC-V
