### ISSUE TITLE
[Question:] How to capture intensity or perceived loudness of a given audio file at regular intervals

### ISSUE THREAD

**Issue by StanSilas** [jameslyons/python_speech_features#61]
If  you are playing a song on your laptop, As you increase the volume from 0 to 100, the audio becomes louder and louder. 

Say I have an .mp3 or .wav , how do I capture this ^ perceived loudness/intensity at regular intervals (may be 0.1 second) in the audio using python speech features? 

Any advice is appreciated. 

Thanks
Vivek

**Comment by morenoh149** [comment]
the amplitude of the waveform is the loudness. So so measure the loudness every 0.1 seconds you get the amplitude at that point in time. Maybe you want something else?

**Comment by venkatsubash2003** [comment]
> 

Do you mean that Loudness is nothing but Amplitude per second?

**Comment by jameslyons** [comment]
Loudness is a perceptual quality of audio related nonlinearly to the audio
waveform. You can approximate it quite well by squaring the time domain
waveform, summing the result and taking the logarithm (cube root can also
work here). If you are interested in rough perceptual loudness per second,
that will do if you sum over 1 second segments of your audio.
