### ISSUE TITLE
rfft vs fft

### ISSUE THREAD

**Issue by mohjaba** [jameslyons/python_speech_features#65]
Hi, in the file "sigproc.py" in line 102 & 103:

`complex_spec = numpy.fft.rfft(frames, NFFT)`
`return numpy.absolute(complex_spec)`

"rfft" return real not complex, you can use "fft" instead or keep it and no need for  "numpy.absolute"

**Comment by jameslyons** [comment]
Rfft is applied to real sequences, it does not return real sequences.
Applied to speech signals it returns a complex spectrum, so we still need
to take the absolute. Documentation here:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.rfft.html
