### ISSUE TITLE
num_frames = 1 + math.floor(...) ? 

### ISSUE THREAD

**Issue by lezasantaizi** [jameslyons/python_speech_features#68]
![image](https://user-images.githubusercontent.com/7878465/43833514-910566ae-9b3d-11e8-86bb-f2e13db8ed8b.png)

**Comment by jameslyons** [comment]
Sorry, I don't understand. do you have a question?

**Comment by lezasantaizi** [comment]
sorry, my fault！
speechpy is wrong ~
![image](https://user-images.githubusercontent.com/7878465/43889701-75dc3b0e-9bf7-11e8-80d7-279ecbb494d0.png)

**Comment by jameslyons** [comment]
no problems :)
