### ISSUE TITLE
Question about hamming window length

### ISSUE THREAD

**Issue by leeeeeeo** [jameslyons/python_speech_features#73]
When using mfcc, the `window` parameter can use `numpy.hamming`, but `numpy.hamming` is a funtion, and it can take an `int` input as number of points in the output window. 
See [numpy.hamming Doc](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.hamming.html).
However, `frame_len` is used in [sigproc.py](https://github.com/jameslyons/python_speech_features/blob/e51df9e484da6c52d30b043f735f92580b9134b4/python_speech_features/sigproc.py#L44)
Could you please how does the `np.hamming` work in mfcc? 
What if I want to input a specific window length?
Thank you !

**Comment by leeeeeeo** [comment]
@jameslyons Thank you for your reply! 
I just want to use hamming window with an argument like [numpy.hamming Doc](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.hamming.html). In the doc, there is an argument M, int. It can control the number of points in the output window.
How to input this argument to `winfunc`?

**Comment by leeeeeeo** [comment]
@jameslyons If this argument is missing, it's meaningless to use hamming window.

**Comment by jameslyons** [comment]
The argument m is just the frame_len correct? Frame_len is passed to the function in the frame_sig function. This is done for you already. Note that when you specify winfunc=np.hamming the function doesnt get called, it gets called later when it is actually used. Try the code i included in the previous comment, it does exactly what you are asking.

**Comment by jameslyons** [comment]
Python allows using functions as variables, e.g.
`def printsomething(x):
    print(x)

y=printsomething
y(10)`

This will print 10. note that no arguments were sent to printsomething until we did y(10). This is what is happening when we use winfunc=np.hamming. It gets used with the correct length later on, we are passing the function as a variable.

**Comment by leeeeeeo** [comment]
@jameslyons Yes, I understand this. I'm wondering whether `mfcc` can slide the hamming window. Actually, I'd like to set winfunc(13). My code is like this: 
`mfcc(audio, samplerate=sample_rate, nfilt=nfilt, lowfreq=lowfreq, highfreq=highfreq, winfunc=lambda x: np.hamming(13))`
And the error is: 
`Exception has occurred: exceptions.ValueError
operands could not be broadcast together with shapes (1467,400) (1467,13) `

**Comment by jameslyons** [comment]
Your frame size is 400 samples, Np.hamming (13) is 13 samples long, so they cant be broadcast. Am i correct that you want your frame length to be 13 samples? Change winlen to be 13/fs.

**Comment by leeeeeeo** [comment]
@jameslyons Hi, I'm new to audio processing. And I'm researching on a computer vision project. The project used MFCC with hamming window in MATLAB. And I'm trying to do this in Python. 
As you can see in [line 5](https://github.com/joonson/yousaidthat/blob/release/utils/runmfcc.m#L5) and [line 7](https://github.com/joonson/yousaidthat/blob/release/utils/runmfcc.m#L7), a `N=13` hamming window is used in MFCC.
In the [MFCC code](https://github.com/joonson/yousaidthat/blob/release/utils/mfcc.m), it's inputs are very similar to your project. So I'm wondering how to get the exact same result between two projects.
Could you please help me getting the same result? Thank you!

**Comment by leeeeeeo** [comment]
That's why I discussing the hamming window problem with you last week. I'm still stucking here... : (

**Comment by jameslyons** [comment]
I suspect youve misunderstood slightly, the hamming window has to be the same length as the frame, which is probably 400 samples or something. 13 is the number of mfcc coefficents. I recommend reading http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/ to understand how all these things fit together

**Comment by jameslyons** [comment]
I read that code you sent, the N in the hamming definition is different to N (number of cepstral coefficients) defined in the header. Hamming is a lambda function so the N in the definition is local only, it could be any other name and work the same. Having said that, getting exactly the same outputs as a different mfcc implementation is really difficult and probably unnecessary. The default parameters with python_speech_features will likely work as good it terms of final accuracy even though the exact numbers in the features might be different.

**Comment by leeeeeeo** [comment]
@jameslyons Thank you! I thought different MFCC implementation should have the same results...  : (

**Comment by hktxt** [comment]
a 3s wav file should produce a 512*678d result under matlab, however, this python gives me a (679, 13)...

**Comment by jameslyons** [comment]
Please start a new issue if you have a question different to the op. Your 512 by 678 dim matrix is very unlikely to be mfccs. More likely power spectrum?
