### ISSUE TITLE
WARNING:root

### ISSUE THREAD

**Issue by Sunilaryal18** [jameslyons/python_speech_features#74]
frame length (1103) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
![image](https://user-images.githubusercontent.com/25361413/48195104-b8be7080-e374-11e8-882a-a552ab4a128a.png)

**Comment by jameslyons** [comment]
Do you have a question? Please read this tutorial: http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/ to better understand the relationship between FFT size and frame length. The FFT size should be longer than the frame length. either increase your fft size, or decrease your frame length, or you can ignore the warning and see how it performs.

**Comment by erikma** [comment]
It made sense to me to auto-generate the FFT size by default. See PR #76

**Comment by jameslyons** [comment]
A good idea. Thanks
