### ISSUE TITLE
logfbank functionstrange winstep size

### ISSUE THREAD

**Issue by LeeYongHyeok** [jameslyons/python_speech_features#79]
Hello, i will use this project, in multimodal speech recognition.

when i use this logfbank function in python3 env, i got 237 frames logfbank feature, using 1.19s wav file.

I check my option, winlen=0.02, winstep=0.01 but output frames are same.

I change the option to winlen=0.04, winstep=0.02, and i got 118 frames. 

what's the matter?? i confuse ...

I installed by 'pip3 install python_speech_features' command, and my os is ubuntu. 

thanks!

**Comment by jameslyons** [comment]
Is it a stereo file? Try either combining the channels or sending in the
channels separately

**Comment by LeeYongHyeok** [comment]
oh, i fix it thank!
