### ISSUE TITLE
Std of log mel-filterbank will be close to zero in some dimension when nfilt == 80.

### ISSUE THREAD

**Issue by TeaPoly** [jameslyons/python_speech_features#85]
import python_speech_features

y, sr = soundfile.read(file, dtype='float32')
log_mfbank = python_speech_features.logfbank(y,
                                               samplerate=16000,
                                               nfilt=80,
                                               winlen=0.025, winstep=0.01,
                                               nfft=512, lowfreq=125, highfreq=7600, preemph=0.97,
                                               winfunc=np.hanning)
std = np.std(features, axis=0)
print(np.min(std))

**Comment by tadangkhoa1999** [comment]
I have same problem. Have you fixed it?
