### ISSUE TITLE
How to ignore the NFFT warning 

### ISSUE THREAD

**Issue by igo312** [jameslyons/python_speech_features#88]
![TX3NH0WQ451{_PJD 7O BML](https://user-images.githubusercontent.com/28484395/69108274-1b316d00-0aaf-11ea-96db-0f34e6e4b991.png)

I don't want to increase the NFFT cause I think it is acceptable to distortion. So may there is any way to ignore the annoying warnings?

I have tried using module `warning` , but it dosen't work.

**Comment by tarasivashchuk** [comment]
@igo312 

These warning are produced using the `logging` module. You can get rid of them using the following:

```
logger = logging.getLogger()
logger.setLevel(logging.ERROR)
```

Refer to further documentation here:
[https://docs.python.org/3/library/logging.html](https://docs.python.org/3/library/logging.html)

**Comment by Razvan4Madrid** [comment]
@tarasivashchuk 
does this NFFT warning, mean that the size of the last frame generated is bigger than 512?
How can i process my data, in order not to get this warning anymore.

The signal i try to process is 39690 samples long and sample rate 44100 Hz.

I get the following:
"WARNING:root:frame length (1103) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid."

Thank you for your help.

**Comment by igo312** [comment]
@Razvan4Madrid use `magspec` wille return a matrix whose shape is `Nx(NFFT/2+1)` or `Nx(NFFT/2)`. So in your case you can set `NFFT>=1103*2`.

And it is about **DFT(discrete fourier transform)**, I think it is necessary to learn it.

**Comment by Razvan4Madrid** [comment]
@igo312 , thank you for your repply.
Shouldn't the function calculate_nfft (samplerate, winlen) calculate and adjust the nfft accordingly to the data processed?

**Comment by igo312** [comment]
> Shouldn't the function calculate_nfft (samplerate, winlen) calculate and adjust the nfft accordingly to the data processed?

Actually you can fix `n_fft` and change `winlen`,`winstep` or in reverse, It's about frequency resolution that's why I recommend you to look for DFT. 

But I think if using a DSP device, there is may some constraints which I don't know very well.
