### ISSUE TITLE
Troubles when porting

### ISSUE THREAD

**Issue by mauritslamers** [jameslyons/python_speech_features#9]
Hi, I am trying to port this algorithm to JavaScript and I am running into the following:

```
feat = numpy.dot(pspec,fb.T)
```
(https://github.com/jameslyons/python_speech_features/blob/master/features/base.py#L56)

The issue I am running into is that pspec and fb here should have the same dimensions, but for some reason they don't. Is there something in the algorithm, some kind of balance between parameters for example, which should cause these two arrays to have the same dimensions?

**Comment by jameslyons** [comment]
the filterbank is designed to match the power spectrum. e.g. pspec might be a 100 by 256 matrix consisting of 100 frames each with 256 fft bins. 'fb' is then designed to be 256 by 26 (assuming 26 filterbanks). FFT size needs to be a parameter to the filterbank creation function so that the sizes match.

**Comment by jameslyons** [comment]
just confirming, this is a matrix multiplication, not an element-wise product.

**Comment by mauritslamers** [comment]
Managed to fix it. Thanks a lot. Now fighting with the different JS implementations of FFTs.

**Comment by mauritslamers** [comment]
I managed to get a working port in JavaScript. Perhaps I missed something in your post (and my background is rather more musical than mathematical), but I have trouble seeing what the output of these functions exactly are, and how they are mapped to the images in your explanation.
